### ISSUE TITLE
Fix call for volunteers on temporary landing page

### ISSUE THREAD

**Issue by tim-schilling** [djangocon/2024-old.djangocon.us#33]
> The homepage link for “Help make the conference happen” goes to https://2024.djangocon.us/news/call-for-2024-volunteers/ which 404s

We need to either create a similar post (copy from 2022 repo), or link to the 2022 repo. I'd prefer to create a similar post and update it to include a reference to the online team.

**Comment by AfiMaameDufie** [comment]
Hi @tim-schilling 
I need some clarification:
Is this the 2022 post  : [2022 call for volunteer post]( https://2022.djangocon.us/news/call-for-2023-volunteers/) / [md file](https://github.com/djangocon/2022.djangocon.us/blob/main/_posts/2022-10-18-call-for-2023-volunteers.md)
Also, what is meant by reference to the online team?

**Comment by tim-schilling** [comment]
@AfiMaameDufie sorry for the confusion, but it looks like you were able to determine what I meant. Thank you!
